---
logging:
  level: INFO
  loggers:
    generation: DEBUG
database:
 driverClass: org.postgresql.Driver
 user: postgres
 password: 12345
 url: jdbc:postgresql://db:5432/invoices
 
 swagger:
   resourcePackage: generation.invoices.resources
